package edu.grinnell.csc207.soundsofsorting.sorts;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import edu.grinnell.csc207.soundsofsorting.sortevents.CompareEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.CopyEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.SortEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.SwapEvent;

/**
 * A collection of sorting algorithms.
 */
public class Sorts {
    /**
     * Swaps indices <code>i</code> and <code>j</code> of array <code>arr</code>.
     * @param <T> the carrier type of the array
     * @param arr the array to swap
     * @param i the first index to swap
     * @param j the second index to swap
     */
    public static <T> void swap(T[] arr, int i, int j) {
        T tmp = arr[i];
        arr[i] = arr[j];
        arr[j] = tmp;
    }

    public static <T> void addCompEvent(List<SortEvent<T>> l, int index1, int index2) {
        List<Integer> compInd = new ArrayList<Integer>();
        compInd.add(index1);
        compInd.add(index2);
        CompareEvent<T> compEvent = new CompareEvent<>(compInd);
        l.add(compEvent);
    }

    public static <T> void addSwapEvent(List<SortEvent<T>> l, int index1, int index2) {
        List<Integer> swapInd = new ArrayList<Integer>();
        swapInd.add(index1);
        swapInd.add(index2);
        SwapEvent<T> swapEvent = new SwapEvent<>(swapInd);
        l.add(swapEvent);
    }

    public static <T> void addCopyEvent(List<SortEvent<T>> l, T copy, int index1, int index2) {
        List<Integer> copyInd = new ArrayList<Integer>();
        copyInd.add(index1);
        copyInd.add(index2);
        CopyEvent<T> copyEvent = new CopyEvent<>(copyInd, copy);
        l.add(copyEvent);
    }

    /**
     * Sorts the array according to the bubble sort algorithm:
     * <pre>
     * [ unprocessed | i largest elements in order ]
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> bubbleSort(T[] arr) {
        List<SortEvent<T>> l = new ArrayList<SortEvent<T>>();
            
        for(int i = arr.length; i>0; i--) {
            for(int j=0; j < i-1; j++) {
                addCompEvent(l, j, j+1);
                if(arr[j].compareTo(arr[j+1]) > 0) {
                    addSwapEvent(l, j, j+1);
                    swap(arr, j, j+1);
                }
            }
        }
        return l;
    }


    /**
     * Sorts the array according to the selection sort algorithm:
     * <pre>
     * [ i smallest elements in order | unprocessed ]
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> selectionSort(
            T[] arr) {
        List<SortEvent<T>> l = new ArrayList<SortEvent<T>>();
        for(int i=0; i<arr.length; i++) {
            int max = i;
            for(int j=i+1; j<arr.length; j++) {
                addCompEvent(l, j, max);
                if(arr[j].compareTo(arr[max]) < 0) {
                    max = j;
                }
            }
            addSwapEvent(l, i, max);
            swap(arr, i, max);
        }
        return null;
    }

    /**
     * Sorts the array according to the insertion sort algorithm:
     * <pre>
     * [ i elements in order | unprocessed ] 
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> insertionSort(
            T[] arr) {
        List<SortEvent<T>> l = new ArrayList<SortEvent<T>>();
        for(int i=0; i<arr.length; i++) {
            for(int j=i; j>0; j--) {
                addCompEvent(l, j, j-1);
                if(arr[j].compareTo(arr[j-1]) < 0) {
                    addSwapEvent(l, j, j-1);
                    swap(arr, j, j-1);
                }
            }
        }
        return null;
    }

    public static <T extends Comparable<? super T>> void merge(T[] arr, T[] tempArr, int left, int right, int end, List<SortEvent<T>> l) {
        int i = left;
        int j = right;
        for(int k = left; k < end; k++) {
            if(i >= right) {
                addCopyEvent(l, arr[j], k, j);
                tempArr[k] = arr[j];
                j++;
            } else if(j >= end) {
                addCopyEvent(l, arr[i], k, i);
                tempArr[k] = arr[i];
                i++;
            } else {
                addCompEvent(l, i, j);
                if(arr[i].compareTo(arr[j]) <= 0) {
                    addCopyEvent(l, arr[i], k, i);
                    tempArr[k] = arr[i];
                    i++;
                } else {
                    addCopyEvent(l, arr[j], k, j);
                    tempArr[k] = arr[j];
                    j++;
                }
            }
        }
        System.arraycopy(tempArr, 0, arr, 0, end);
    }

    public static <T extends Comparable<? super T>> void mergeSortHelper(T[] arr, T[] tempArr, int start, int end, List<SortEvent<T>> l) {
        int left = start;
        int right = (end+start) / 2;
        if(left != right) {
            mergeSortHelper(arr, tempArr, left, right, l);
            mergeSortHelper(arr, tempArr, right, end, l);
        }
        merge(arr, tempArr, left, right, end, l);
    }

    /**
     * Sorts the array according to the merge sort algorithm.
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> mergeSort(
            T[] arr) {
        List<SortEvent<T>> l = new ArrayList<SortEvent<T>>();
        T[] tempArr = Arrays.copyOf(arr, arr.length);
        mergeSortHelper(arr, tempArr, 0, arr.length, l);
        return l;
    }


    /**
     * Sorts the array according to the quick sort algorithm.
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<Integer>> quickSort(T[] arr) {
        //TODO: implement for corrections
        mergeSort(arr);

        return null;
    }

    public static <T> void eventSort(T[] l, List<SortEvent<T>> events) {
        for(int i=0; i<events.size(); i++) {
            events.get(i).apply(l);
        }
    } 

}
